### ISSUE TITLE
Add unique identifier

### ISSUE THREAD

**Issue by MichaelMBishop** [nonviolent-action-lab/crowd-counting-consortium#4]
It would be nice to add a unique identifier... the main thing is to have one, of any kind, but personally I'd just go with an integer that increments with each event that's added. It doesn't really matter if the order means anything for entries already added. Additionally, and optionally, you could add a new column to record "DateAdded" to the database, i.e., when the data is moved from the google sheet into the csv.

**Comment by nonviolent-action-lab** [comment]
This would certainly be easy to do.

Before we add another column to the stored database, though, may I ask: why do you think it's important to have this? The only circumstance where it would add information you couldn't get by generating your own after ingesting the data would be if two rows matched exactly on all current fields. And I'm virtually certain that won't happen. What am I overlooking, or what use case am I not considering?

**Comment by MichaelMBishop** [comment]
Thanks for your consideration! As you point out there are probably multiple considerations. 

As you can imagine, a unique identifier makes a lot of things a little bit easier. It also makes a few things a lot easier, and providing it might reduce errors others might make. 

To get specific... 
Say I use this data today, and then a month down the road you've updated it. 
Rather than overwrite the data I've been using, I might want to take only the new records you provided.
A unique identifier "built in" obviously makes that easier. 
It also makes it easier to discover which records have data that changed over time. 

Perhaps the old records will never change? In that case the unique ID makes it much easier to prove that none of the older records had any changes!

By making the data version-controlled and available on github you already make it more open, and support more reproducible analyses than the vast majority of non-static datasets. But adding a unique identifier for each row really does take it another step forward in making it easier for other people to reproduce eachothers' data analyses...  

Another point, possibly the clearest one... Perhaps I wanted to create and opensource additional data that could be joined with yours. If I don't have a guarantee about which fields are necessary and sufficient to guarantee uniqueness, things get messy. To achieve maximum quality control I need to basically duplicate your whole dataset and then add my own columns.

**Comment by nonviolent-action-lab** [comment]
Okay, that makes sense, and thanks for clarifying.

Unfortunately, I can't reliably do this as part of the data compilation and cleaning process. What you need is a unique identifier for each event in the CCC's Google Sheets, assigned at the point of data creation. All I can do is add one after ingesting their data, but an ID assigned after data ingestion won't provide any of the version control you're after, because it will be ignorant of any reordering of the rows or additions or subtractions in the Google Sheet prior to ingestion.

So I'm going to close this issue here, but I will also recommend to CCC that they consider adding unique IDs to their sheets for the reasons you describe.
