### ISSUE TITLE
Instead of `Final` -> `Version`?

### ISSUE THREAD

**Issue by MichaelMBishop** [nonviolent-action-lab/crowd-counting-consortium#5]
Instead of a binary variable, you could call it `Version` and then give yourself the freedom to revise past data if necessary. `0` could still mean un-finalized, `1` still indicates "intended to be final" and then > 1 indicates revisions. If you do ever revise data, you should also add a `DateRevised` column to make it easier for users of the data to see when data was revised.

**Comment by nonviolent-action-lab** [comment]
This certainly would be ideal. The problem is that it would require coordination with CCC; I (Jay) am not directly involved in the production of CCC's raw data; and I'm not in a position to task the people (often volunteers) who are. So, for now, the only information we're going to have is that sheet-level (i.e., month-level) indicator of whether or not CCC considers those events to be finalized.
